//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookOkan.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OutlookOkan.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert keywords.
        /// </summary>
        public static string AlertKeyword {
            get {
                return ResourceManager.GetString("AlertKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords to alert.
        /// </summary>
        public static string AlertKeywordInfo {
            get {
                return ResourceManager.GetString("AlertKeywordInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert recipients.
        /// </summary>
        public static string AlertMailAddress {
            get {
                return ResourceManager.GetString("AlertMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerting recipients or domains.
        /// </summary>
        public static string AlertMailAddressAndDomain {
            get {
                return ResourceManager.GetString("AlertMailAddressAndDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicable recipients.
        /// </summary>
        public static string ApplicableDestination {
            get {
                return ResourceManager.GetString("ApplicableDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicable keywords.
        /// </summary>
        public static string ApplicableKeywords {
            get {
                return ResourceManager.GetString("ApplicableKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutlookOkan.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached is an encrypted ZIP file..
        /// </summary>
        public static string AttachedIsAnEncryptedZipFile {
            get {
                return ResourceManager.GetString("AttachedIsAnEncryptedZipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Cc/Bcc addition(by attachments).
        /// </summary>
        public static string AutoAddCCorBCCByAttachedFile {
            get {
                return ResourceManager.GetString("AutoAddCCorBCCByAttachedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Cc/Bcc addition(by keywords).
        /// </summary>
        public static string AutoAddCCorBCCByKeyword {
            get {
                return ResourceManager.GetString("AutoAddCCorBCCByKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords that automatically add Ccs or Bccs..
        /// </summary>
        public static string AutoAddCCorBCCByKeywordInfo {
            get {
                return ResourceManager.GetString("AutoAddCCorBCCByKeywordInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Cc/Bcc addition(by recipients).
        /// </summary>
        public static string AutoAddCCorBCCByMailAddressOrDomain {
            get {
                return ResourceManager.GetString("AutoAddCCorBCCByMailAddressOrDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipients or domains that automatically add Ccs or Bccs..
        /// </summary>
        public static string AutoAddCCorBCCByMailAddressOrDomainInfo {
            get {
                return ResourceManager.GetString("AutoAddCCorBCCByMailAddressOrDomainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added automatically..
        /// </summary>
        public static string AutoAddDestination {
            get {
                return ResourceManager.GetString("AutoAddDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically add recipients..
        /// </summary>
        public static string AutoAddMailAddress {
            get {
                return ResourceManager.GetString("AutoAddMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sender&apos;s Email address was automatically added to the To. (because the To no longer exists due to auto change to Bcc.).
        /// </summary>
        public static string AutoAddSendersAddressToAlert {
            get {
                return ResourceManager.GetString("AutoAddSendersAddressToAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-check setting.
        /// </summary>
        public static string AutoCheckConfig {
            get {
                return ResourceManager.GetString("AutoCheckConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The members&apos; email addresses will be auto-checked..
        /// </summary>
        public static string AutoCheckMembersAddress {
            get {
                return ResourceManager.GetString("AutoCheckMembersAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The internal domain recipients will be auto-checked..
        /// </summary>
        public static string AutoCheckSameDomain {
            get {
                return ResourceManager.GetString("AutoCheckSameDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Settings.
        /// </summary>
        public static string BasicSettings {
            get {
                return ResourceManager.GetString("BasicSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled sending this email..
        /// </summary>
        public static string CanceledSendingMail {
            get {
                return ResourceManager.GetString("CanceledSendingMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled sending this email. You can reedit this.
        ///To send this email, you must click on the Send button.
        ///(Closing the edit screen will not send this email.).
        /// </summary>
        public static string CanceledSendingMailMessage {
            get {
                return ResourceManager.GetString("CanceledSendingMailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new version of this add-in.
        ///Do you want to download it?.
        /// </summary>
        public static string CanGetNewVersion {
            get {
                return ResourceManager.GetString("CanGetNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cc/Bcc.
        /// </summary>
        public static string CCorBCC {
            get {
                return ResourceManager.GetString("CCorBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the display language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The display language of the ribbon (menu) is updated when Outlook is restarted..
        /// </summary>
        public static string ChangeRibbonLanguageInfo {
            get {
                return ResourceManager.GetString("ChangeRibbonLanguageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the new version..
        /// </summary>
        public static string CheckNewVersion {
            get {
                return ResourceManager.GetString("CheckNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noraneko Inc..
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation before sending an email..
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to send this email?.
        /// </summary>
        public static string ConfirmationMessage1 {
            get {
                return ResourceManager.GetString("ConfirmationMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After checking all items, you can press send button..
        /// </summary>
        public static string ConfirmationMessage2 {
            get {
                return ResourceManager.GetString("ConfirmationMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact group.
        /// </summary>
        public static string ContactGroup {
            get {
                return ResourceManager.GetString("ContactGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) 2020 Noraneko Inc..
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export CSV.
        /// </summary>
        public static string CSVExport {
            get {
                return ResourceManager.GetString("CSVExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import CSV.
        /// </summary>
        public static string CSVImport {
            get {
                return ResourceManager.GetString("CSVImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t import CSV file with wrong format..
        /// </summary>
        public static string CSVImportAlert {
            get {
                return ResourceManager.GetString("CSVImportAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The warning keyword is included in the body of the email..
        /// </summary>
        public static string DefaultAlertMessage {
            get {
                return ResourceManager.GetString("DefaultAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deferred delivery.
        /// </summary>
        public static string DeferredDelivery {
            get {
                return ResourceManager.GetString("DeferredDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the email address or domain you want to deferred delivery..
        /// </summary>
        public static string DeferredDeliveryEmailAddressOrDomainInfo {
            get {
                return ResourceManager.GetString("DeferredDeliveryEmailAddressOrDomainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deferred delivery time.(min).
        /// </summary>
        public static string DeferredDeliveryMinutes {
            get {
                return ResourceManager.GetString("DeferredDeliveryMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deferred delivery time.(min).
        /// </summary>
        public static string DeferredDeliveryTime {
            get {
                return ResourceManager.GetString("DeferredDeliveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipients.
        /// </summary>
        public static string DestinationEmailaddress {
            get {
                return ResourceManager.GetString("DestinationEmailaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip the confirmation window.
        /// </summary>
        public static string DoNotShowConfirmationScreen {
            get {
                return ResourceManager.GetString("DoNotShowConfirmationScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If there is a sentence &quot;attached file&quot; in the text and there is no attached file, warn about that..
        /// </summary>
        public static string EnableForgottenToAttachAlert {
            get {
                return ResourceManager.GetString("EnableForgottenToAttachAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted Zip (Beta).
        /// </summary>
        public static string EncryptedZipBeta {
            get {
                return ResourceManager.GetString("EncryptedZipBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusion settings.
        /// </summary>
        public static string ExclusionSettings {
            get {
                return ResourceManager.GetString("ExclusionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export..
        /// </summary>
        public static string ExportFailed {
            get {
                return ResourceManager.GetString("ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As the external domains of To and Cc are above the threshold, the external domain recipients has been changed to Bcc..
        /// </summary>
        public static string ExternalDomainsChangeToBccAlert {
            get {
                return ResourceManager.GetString("ExternalDomainsChangeToBccAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External domains warning and auto change to Bcc.
        /// </summary>
        public static string ExternalDomainsWarningAndAutoChangeToBcc {
            get {
                return ResourceManager.GetString("ExternalDomainsWarningAndAutoChangeToBcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the information..
        /// </summary>
        public static string FailedToGetInformation {
            get {
                return ResourceManager.GetString("FailedToGetInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word &quot;attached file&quot; is in the text, but there is no attachment..
        /// </summary>
        public static string ForgottenToAttachAlert {
            get {
                return ResourceManager.GetString("ForgottenToAttachAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the members of an Contact group..
        /// </summary>
        public static string GetMembersOfTheContactGroup {
            get {
                return ResourceManager.GetString("GetMembersOfTheContactGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the members of an Exchange distribution list. (It may take a long time.).
        /// </summary>
        public static string GetMembersOfTheExDistList {
            get {
                return ResourceManager.GetString("GetMembersOfTheExDistList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the members of an Exchange distribution list or an Contact group.
        /// </summary>
        public static string GetMembersOfTheList {
            get {
                return ResourceManager.GetString("GetMembersOfTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Delete row: Select the row and press the delete key..
        /// </summary>
        public static string HowToDeleteRow {
            get {
                return ResourceManager.GetString("HowToDeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        public static string HTML {
            get {
                return ResourceManager.GetString("HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If all recipient&apos;s domains are internal domain, skip the confirmation window..
        /// </summary>
        public static string IfAllSameDomain {
            get {
                return ResourceManager.GetString("IfAllSameDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If there is no check target in the recipients, skip the confirmation window. (e.g., if all recipients are included in the allowlist.).
        /// </summary>
        public static string IfAllWhite {
            get {
                return ResourceManager.GetString("IfAllWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import/Export.
        /// </summary>
        public static string ImportAndExport {
            get {
                return ResourceManager.GetString("ImportAndExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Alerts..
        /// </summary>
        public static string ImportantAlert {
            get {
                return ResourceManager.GetString("ImportantAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import..
        /// </summary>
        public static string ImportFailed {
            get {
                return ResourceManager.GetString("ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter &quot;Cc&quot; or &quot;Bcc&quot;..
        /// </summary>
        public static string InputCCorBCC {
            get {
                return ResourceManager.GetString("InputCCorBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the deferred time in minutes..
        /// </summary>
        public static string InputDeferredDeliveryTime {
            get {
                return ResourceManager.GetString("InputDeferredDeliveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the domain..
        /// </summary>
        public static string InputDomain {
            get {
                return ResourceManager.GetString("InputDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the domain from @..
        /// </summary>
        public static string InputDomainInfo {
            get {
                return ResourceManager.GetString("InputDomainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email address or domain..
        /// </summary>
        public static string InputMailaddressOrDomain {
            get {
                return ResourceManager.GetString("InputMailaddressOrDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name. (ex. Company name).
        /// </summary>
        public static string InputNameInfo {
            get {
                return ResourceManager.GetString("InputNameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal domain.
        /// </summary>
        public static string InternalDomain {
            get {
                return ResourceManager.GetString("InternalDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipients (Bcc) contains an address or domain that has been registered as an alert..
        /// </summary>
        public static string IsAlertAddressBccAlert {
            get {
                return ResourceManager.GetString("IsAlertAddressBccAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipients (Cc) contains an address or domain that has been registered as an alert..
        /// </summary>
        public static string IsAlertAddressCcAlert {
            get {
                return ResourceManager.GetString("IsAlertAddressCcAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This recipient may be unrelated to the intended destination..
        /// </summary>
        public static string IsAlertAddressMaybeIrrelevant {
            get {
                return ResourceManager.GetString("IsAlertAddressMaybeIrrelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipients (To) contains an address or domain that has been registered as an alert..
        /// </summary>
        public static string IsAlertAddressToAlert {
            get {
                return ResourceManager.GetString("IsAlertAddressToAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An executable file (.exe) is attached..
        /// </summary>
        public static string IsAttachedExe {
            get {
                return ResourceManager.GetString("IsAttachedExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external recipient of To and Cc are automatically converted to Bcc 
        ///when the recipients (To/Cc) has a large number of external domains..
        /// </summary>
        public static string IsAutoChangeToBccWhenLargeNumberOfExternalDomains {
            get {
                return ResourceManager.GetString("IsAutoChangeToBccWhenLargeNumberOfExternalDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a 10Mbyte or larger file attached to this email..
        /// </summary>
        public static string IsBigAttachedFile {
            get {
                return ResourceManager.GetString("IsBigAttachedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation window could not be displayed..
        /// </summary>
        public static string IsCanNotShowConfirmation {
            get {
                return ResourceManager.GetString("IsCanNotShowConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable this feature if the recipient&apos;s domains are all internal domains..
        /// </summary>
        public static string IsDoNotUseXIfAllRecipientsAreInternalDomain {
            get {
                return ResourceManager.GetString("IsDoNotUseXIfAllRecipientsAreInternalDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached files with an extension other than &quot;.zip&quot; also detect whether they are encrypted ZIP or not..
        /// </summary>
        public static string IsEnableAllAttachedFilesAreDetectEncryptedZip {
            get {
                return ResourceManager.GetString("IsEnableAllAttachedFilesAreDetectEncryptedZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipients are sorted by domain on the confirmation screen..
        /// </summary>
        public static string IsEnableRecipientsAreSortedByDomain {
            get {
                return ResourceManager.GetString("IsEnableRecipientsAreSortedByDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file embedded in an HTML mail is not treated as an attachment..
        /// </summary>
        public static string IsNotTreatedAsAttachmentsAtHtmlEmbeddedFiles {
            get {
                return ResourceManager.GetString("IsNotTreatedAsAttachmentsAtHtmlEmbeddedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending is prohibited when an encrypted ZIP file is attached..
        /// </summary>
        public static string IsProhibitedWhenEncryptedZipIsAttached {
            get {
                return ResourceManager.GetString("IsProhibitedWhenEncryptedZipIsAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending is prohibited when the recipients (To/Cc) has a large number of external domains..
        /// </summary>
        public static string IsProhibitedWhenLargeNumberOfExternalDomains {
            get {
                return ResourceManager.GetString("IsProhibitedWhenLargeNumberOfExternalDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the recipients contains multiple external domains, display the confirmation window. (Doesn&apos;t skip the confirmation window.).
        /// </summary>
        public static string IsShowConfirmationToMultipleDomain {
            get {
                return ResourceManager.GetString("IsShowConfirmationToMultipleDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip confirmation window..
        /// </summary>
        public static string IsSkipConfirmation {
            get {
                return ResourceManager.GetString("IsSkipConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip the confirmation window when you send an email only to the selected recipients..
        /// </summary>
        public static string IsSkipConfirmationInfo {
            get {
                return ResourceManager.GetString("IsSkipConfirmationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display a warning when an encrypted ZIP file is attached..
        /// </summary>
        public static string IsWarningWhenEncryptedZipIsAttached {
            get {
                return ResourceManager.GetString("IsWarningWhenEncryptedZipIsAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a warning when the recipients (To/Cc) has a large number of external domains..
        /// </summary>
        public static string IsWarningWhenLargeNumberOfExternalDomains {
            get {
                return ResourceManager.GetString("IsWarningWhenLargeNumberOfExternalDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of external domains in To and Cc is higher than the threshold. Please reconfirm the pros and cons of the sending..
        /// </summary>
        public static string LargeNumberOfExternalDomainAlert {
            get {
                return ResourceManager.GetString("LargeNumberOfExternalDomainAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient address/domain.
        /// </summary>
        public static string MailAddressAndDomain {
            get {
                return ResourceManager.GetString("MailAddressAndDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message body (Plain-text).
        /// </summary>
        public static string MailBody {
            get {
                return ResourceManager.GetString("MailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Infomation.
        /// </summary>
        public static string MailInfo {
            get {
                return ResourceManager.GetString("MailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string MailType {
            get {
                return ResourceManager.GetString("MailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name/Domain.
        /// </summary>
        public static string NameAndDomain {
            get {
                return ResourceManager.GetString("NameAndDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no important alerts..
        /// </summary>
        public static string NoAlert {
            get {
                return ResourceManager.GetString("NoAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * The processing of emails with attachments may take longer..
        /// </summary>
        public static string NoticeOfIsEnableAllAttachedFilesAreDetectEncryptedZip {
            get {
                return ResourceManager.GetString("NoticeOfIsEnableAllAttachedFilesAreDetectEncryptedZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of external domains in To and Cc is above the threshold..
        /// </summary>
        public static string ProhibitedWhenLargeNumberOfExternalDomainsAlert {
            get {
                return ResourceManager.GetString("ProhibitedWhenLargeNumberOfExternalDomainsAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich-text.
        /// </summary>
        public static string RichText {
            get {
                return ResourceManager.GetString("RichText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings have been updated..
        /// </summary>
        public static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a CSV file..
        /// </summary>
        public static string SelectCSVFile {
            get {
                return ResourceManager.GetString("SelectCSVFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select where you want to save it..
        /// </summary>
        public static string SelectSaveDestination {
            get {
                return ResourceManager.GetString("SelectSaveDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending prohibited.
        /// </summary>
        public static string SendingForbid {
            get {
                return ResourceManager.GetString("SendingForbid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prohibited recipients..
        /// </summary>
        public static string SendingForbidAddress {
            get {
                return ResourceManager.GetString("SendingForbidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you check this box, you can&apos;t send an email to the recipient or include the keyword..
        /// </summary>
        public static string SendingForbidInfo {
            get {
                return ResourceManager.GetString("SendingForbidInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to send this email?.
        /// </summary>
        public static string SendMailConfirmation {
            get {
                return ResourceManager.GetString("SendMailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send on behalf or Send As..
        /// </summary>
        public static string SentOnBehalf {
            get {
                return ResourceManager.GetString("SentOnBehalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example of settings..
        /// </summary>
        public static string SettingExample {
            get {
                return ResourceManager.GetString("SettingExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords: Confidential
        ///Alerting text: It includes the phrase &quot;Confidential&quot;.
        ///
        ///Register the keywords to be alert and their alerting text.
        ///
        ///If the alerting text is blank, the confirmation screen will show the default alerting text..
        /// </summary>
        public static string SettingExampleAlertKeyword {
            get {
                return ResourceManager.GetString("SettingExampleAlertKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address: info@noraneko.co.jp
        ///or
        ///Domain: @noraneko.co.jp
        ///
        ///Register an email address or domain.
        ///
        ///If you send an email to an email address or domain that you have registered here, you will receive an alert in advance..
        /// </summary>
        public static string SettingExampleAlertMailAddress {
            get {
                return ResourceManager.GetString("SettingExampleAlertMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an email has an encrypted ZIP file attached to it, you can display a warning or prohibit the sending of that email..
        /// </summary>
        public static string SettingExampleAttachments {
            get {
                return ResourceManager.GetString("SettingExampleAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: Cc or Bcc
        ///Email address: boss@noraneko.co.jp
        ///
        ///When you send an email with a file attached, The specified address is automatically added to the Cc or Bcc..
        /// </summary>
        public static string SettingExampleAutoAddCCorBCCByAttachedFile {
            get {
                return ResourceManager.GetString("SettingExampleAutoAddCCorBCCByAttachedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: Cc or Bcc
        ///Keywords: Confidential
        ///Email address: boss@noraneko.co.jp
        ///
        ///When the keywords are included in the mail, The specified address is automatically added to the Cc or Bcc..
        /// </summary>
        public static string SettingExampleAutoAddCCorBCCByKeyword {
            get {
                return ResourceManager.GetString("SettingExampleAutoAddCCorBCCByKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: Cc or Bcc
        ///To: warning@xxxxxxx.com
        ///Email address: boss@noraneko.co.jp
        ///
        ///When sending mail to registered recipients and domains, The specified address is automatically added to the Cc or Bcc..
        /// </summary>
        public static string SettingExampleAutoAddCCorBCCByMailAddressOrDomain {
            get {
                return ResourceManager.GetString("SettingExampleAutoAddCCorBCCByMailAddressOrDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address: info@noraneko.co.jp
        ///or
        ///Domain: @noraneko.co.jp
        ///
        ///Register your email address or domain and register the deferred time by the minute.
        ///
        ///* If you register only @, you can register the standard deferred time of all mails.
        ///
        ///* If multiple conditions are met, the longest deferred time will be applied..
        /// </summary>
        public static string SettingExampleDeferredDelivery {
            get {
                return ResourceManager.GetString("SettingExampleDeferredDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the number of external domains to be used as a basis for warnings and automatic change to Bcc, and turn each one on or off.
        ///
        ///If the To does not exist after automatic change to Bcc, the sender&apos;s address will be automatically added to the To..
        /// </summary>
        public static string SettingExampleExternalDomainsWarningAndAutoChangeToBcc {
            get {
                return ResourceManager.GetString("SettingExampleExternalDomainsWarningAndAutoChangeToBcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain: @noraneko.co.jp
        ///
        ///Register a domain to be handled as an internal (company) domain.
        ///
        ///The domain of the sender&apos;s email address is always treated as an internal domain..
        /// </summary>
        public static string SettingExampleInternalDomainList {
            get {
                return ResourceManager.GetString("SettingExampleInternalDomainList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: Noraneko Inc
        ///Domain: @noraneko.co.jp
        ///
        ///Register the name (ex. Company name) and domain.
        ///
        ///Displays a warning if the name in the email body and the recipients domain do not match..
        /// </summary>
        public static string SettingExampleNameAndDomain {
            get {
                return ResourceManager.GetString("SettingExampleNameAndDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address: info@noraneko.co.jp
        ///or
        ///Domain: @noraneko.co.jp
        ///
        ///Register Email address or domain.
        ///
        ///The relevant recipients will be pre-checked in the confirmation screen..
        /// </summary>
        public static string SettingExampleWhiteList {
            get {
                return ResourceManager.GetString("SettingExampleWhiteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The export is now complete..
        /// </summary>
        public static string SuccessfulExport {
            get {
                return ResourceManager.GetString("SuccessfulExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import is now complete..
        /// </summary>
        public static string SuccessfulImport {
            get {
                return ResourceManager.GetString("SuccessfulImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of external domains of the recipients (To/Cc) to be covered by this feature..
        /// </summary>
        public static string TargetToAndCcExternalDomainsNum {
            get {
                return ResourceManager.GetString("TargetToAndCcExternalDomainsNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * If the external domain included in the To and Cc of the email is greater than or equal to this setting, 
        ///this feature will be applied..
        /// </summary>
        public static string TargetToAndCcExternalDomainsNumInfo {
            get {
                return ResourceManager.GetString("TargetToAndCcExternalDomainsNumInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain-text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 2.5.4.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerting text.
        /// </summary>
        public static string WarningText {
            get {
                return ResourceManager.GetString("WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerting text on confirmation window..
        /// </summary>
        public static string WarningTextInfo {
            get {
                return ResourceManager.GetString("WarningTextInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowlist.
        /// </summary>
        public static string WhiteList {
            get {
                return ResourceManager.GetString("WhiteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This add-in is the latest version..
        /// </summary>
        public static string YouHaveLatest {
            get {
                return ResourceManager.GetString("YouHaveLatest", resourceCulture);
            }
        }
    }
}
